###################
#                 #
# NoJoinMessage+  #
#                 #
###################
#
# enable-message: true/false - Do you want this message enabled?
# 
# message: '&a&l+ {player}' - What should the message be?

join:
    enable-message: true
    message: '&a&l+ {player}'
leave:
    enable-message: true
    message: '&c&l- {player}'