###################
#                 #
# NoJoinMessage+  #
#                 #
###################
#
# enable-message: - Do you want this message enabled?
# 
# message: - What should the message be?

join:
    enable-message: true
    message: '&a&l+ {player}'
leave:
    enable-message: true
    message: '&c&l- {player}'