name: NoJoinMessage
main: me.stewez.NoJoinMessage.NoJoinMessage
version: 1.7
author: stewez
website: http://dev.bukkit.org/bukkit-plugins/nojoinmessage/

commands:
    nojoinmessage:
        aliases: [njm]
        description: The main command for NoJoinmessage!
        
permissions:
    nojoinmessage.reload:
        description: Reload the config file.
        default: op
    nojoinmessage.fake:
        description: Fake join a player.
        default: op